### ISSUE TITLE
Ubuntu 20.04 Mirror Root on ZFS: grub not updated after a restore.

### ISSUE THREAD

**Issue by ddnexus** [ubuntu/zsys#163] opened 2020-09-11 07:58 UTC
Before filing a proper bug report, please help me to determine if it is a bug or some other problem.

I followed the instruction for the manual installation for Ubuntu 20.04 mirror root [here](https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html).

In the mirror setup `/boot/grub` is mounted from `bpool` and not from the EFI partition as it is for the single disk setup.

That seems to cause the inability to update the grub menu after a revert. Indeed - after a revert - I see in `zpool history` that `rpool` has been cloned as expected, while `bpool` did not. 

It looks like in the restored state `bpool` is a read-only snapshot, so you cannot update the grub menu. It will simply stay frozen, no matter what you do, so no way to reboot automatically in the same state. Grub will always show the old menu before the restore (so no other history menu appears, even if you save state manually).

I guess that a `bpool` snapshot after a restore would not cause any problem in single disk setup because grub will write/update its menu in the EFI partition, while in the mirror setup (restored state) that seems to be impossible since `bpool` seems to be not writable.

Does this look like a bug or did I miss some extra configuration?

Shouldn't zsys create a clone also for `bpool` after a restore, so it will allow grub to be updated? 

Thanks.

**Comment by ddnexus** [comment] 2020-09-11 11:04
Maybe I tried to guess too much :/
I just verified that I can write to `/boot/grub` so  my theory about the reason the grub menu does not get updated is wrong.

Despite the reason being the wrong one, I cannot automatically reboot in the latest restored state. I still have to manually restore to the last saved snapshot with the history menu in order to get the same state with the same kernel. 

Souldn't zsys update grub default menu after a restore?

**Comment by didrocks** [comment] 2020-09-11 11:25
hey!

ZSys will only update the grub menu if it has a successful boot after a revert. What we consider a successful boot is if the `default.target` is reached and activated. Is there anything that can block that target? (you can check with systemctl commands)

**Comment by ddnexus** [comment] 2020-09-11 13:51
Thanks for the answer. I will have to research about what you say about systemctl. No idea how to check for what you ask.

Meanwhile I discovered that after the revert, the `/boot/grub/grub.conf` is written right, i.e. it is pointing to the right id for the default boot. (maybe because I also manually upated it). With that file, grub would reboot the right state. The problem is that the file is not available at boot. At boot the same file is a different version (pointing to the old state).

In practice the grub menu is not unique: it is updated in different states as it should be at boot, BUT the right file will be available only AFTER reverting, hence it will not work. It looks like the chicken and egg problem.

It looks like with grub in EFI there would be always one single version of the grub menu (the last one updated), but with grub in `bpool` the update gets saved in the reverted state itself. After rebooting the old file will be used (which does not contain the "right" default params but the old ones).

Does that have something to do with reaching the `default.target` that you mentioned?

**Comment by didrocks** [comment] 2020-09-11 13:58
It doesn’t seem related to default.target then. I think this is an issue with your manual mirror setup: We do create in ubiquity the configuration to have `/boot/grub` as a bindmount of `/boot/efi/grub` in the destination, hence having a single version. You should only have an empty `/boot/grub` directory in your bpool datasets. I suggest you check your manual install to reproduce what we craft in the installer by default so that you have this single `grub`.

I wrote about this (and the issue of grub revert without it) on https://didrocks.fr/2020/06/11/zfs-focus-on-ubuntu-20.04-lts-zsys-partition-layout/ :)

**Comment by ddnexus** [comment] 2020-09-11 14:19
Thank you! That makes a lot of sense to me indeed. 

Here is what is written in the instructions (and what I actually did in my setup):

```
zfs create -o canmount=noauto -o mountpoint=/boot \
    bpool/BOOT/ubuntu_$UUID
zfs mount bpool/BOOT/ubuntu_$UUID
```

"For a mirror or raidz topology, create a dataset for /boot/grub:
`zfs create bpool/BOOT/ubuntu_$UUID/grub`"

So after what you just said, the instructions seem wrong. Are they wrong?

**Comment by didrocks** [comment] 2020-09-11 14:25
I’m unsure where you took those instructions, but indeed, they don’t match the ZSys default setup layout.

**Comment by ddnexus** [comment] 2020-09-11 14:34
[Ubuntu 20.04 Root on ZFS (\step-3-system-installation\)](https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html#step-3-system-installation) the third point in that section...

I will ask there why grub is not on EFI. Thank you for your help!

**Comment by didrocks** [comment] 2020-09-11 14:35
You’re welcome! I’m closing this bug thus :+1:

**Closed by didrocks** 2020-09-11 14:35 UTC

**Comment by ddnexus** [comment] 2020-09-11 14:38
Yes, not a bug indeed :)
Thank you!

**Comment by rlaager** [comment] 2020-09-11 21:44
@didrocks This is a _mirrored_ setup (which is not supported by Ubiquiti). My thinking (correct me if I'm wrong) is that we can't have `/boot/grub` be `/boot/efi/grub` because `/boot/efi` only exists on one disk.

**Comment by rlaager** [comment] 2020-09-12 04:21
@didrocks Why does `zsys` set `canmount=off` on bpool/grub? That's what was breaking `bpool/grub` in the original version of the 20.04 HOWTO, which I then [changed to](https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html#boot-grub-not-mounted) `bpool/BOOT/ubuntu_$UUID/grub`. That [seems to be the problem here](https://github.com/openzfs/openzfs-docs/issues/55#issuecomment-691401410).

**Comment by ddnexus** [comment] 2020-09-14 06:37
@rlaager I just tried to use `bpool/grub` and it appears to work. Either zsys changed or it didn't trigger the problem yet on my system. When exactly the switch from on to off is supposed to happen?

**Comment by didrocks** [comment] 2020-09-14 07:06
ZSys isn’t supposed to change anything outside of `<pool>/BOOT`, `<pool>/ROOT` and `<pool>/USERDATA`: ZFS or user properties are left untouched. This is why I’m surprised that `canmount=off`. If there is a clear and easy to test reproducer, I’m happy to have a look.

**Comment by ddnexus** [comment] 2020-09-14 07:59
@didrocks I tried `bpool/grub` and it seems to work as I wrote before your last comment, BUT something weird keep happening, so I don't know if it has something to do with zsys now.

I restore a state, the generated grub.cgf is indicating as the first (default) menu a specific state id for root and kernel. So far so good. But then when I reboot from the state and enter in the grub menu, the first menu has a different state id, hence it does not boot the same restored state I was in before the reboot. (It looks like grub.cfg is a different file).

At the beginning of this post I was thinking it was because `/boot/grub` was mounted from `bpool/BOOT/ubuntu_ID/grub` dataset, which is not persistent (and indeed that is a big probem). So I changed it first to `bpool/GRUB/grub`, and then to `bpool/grub` and the problem is exactly the same.

No idea what cause grub to switch the grub.cfg but something does. Please, could you indicate the steps to check in order to pinpoint the cause? I am getting crazy with this thing!

**Comment by ddnexus** [comment] 2020-09-14 08:07
Now I am not even sure what to expect from a restored state anymore. I am thinking zsys updates the grub menu when restores a state successfully (i.e. it actually boots successfully), so at the next boot the first default menu will be automatically picked up and the state will be the same restored one of the previous boot.

Is that what is supposed to happen?
Thank you!

**Comment by didrocks** [comment] 2020-09-14 09:03
>  so at the next boot the first default menu will be automatically picked up and the state will be the same restored one of the previous boot.
> Is that what is supposed to happen?
This is exactly what is supposed to happen.

My guess is that you installed grub twice in your boot configuration: either one on each mbr/gpt disk or in the mbr and in one partition (this happened to me in my tests). So, basically, we are updating the grub menu at boot (the only one we see from the system), but your system is configured to boot from another grub.

Do you see the boot menu evolving over time? (like having more snapshots and such) or is like stuck in time?
You should try to run install-grub on the correct disk to ensure that the one we have setup is the one we are booting (I can’t give you the exact command as I’m unsure about your setup, and this is why it’s not officially supported), but this is my best guess of what is happening to your system.

**Comment by ddnexus** [comment] 2020-09-14 10:37
Thank you again-and-never-enough for your support Didier!!!

@rlaager it looks like the "How-to" upstream suggests to do exactly what @didrocks says is the problem;

> For a mirror or raidz topology, run this for the additional disk(s), incrementing the “2” to “3” and so on for both /boot/efi2 and ubuntu-2:
    ```
    cp -a /boot/efi/EFI /boot/efi2
    grub-install --target=x86_64-efi --efi-directory=/boot/efi2 \
        --bootloader-id=ubuntu-2 --recheck --no-floppy
    ```

AS the result I ran:
```
grub-install --target=x86_64-efi --efi-directory=/boot/efi0 \
    --bootloader-id=ubuntu-0 --recheck --no-floppy
cp -a /boot/efi0/EFI /boot/efi1
grub-install --target=x86_64-efi --efi-directory=/boot/efi1 \
    --bootloader-id=ubuntu-1 --recheck --no-floppy
```

I thought that since we are dealing with mirrors - in case of failure of the boot-disk - then the other will leave you with a non-bootable system, which kind of defeats the goal of mirroring. That setup seems to try to avoid that. But if we still update only one grub, it looks kind of pointless now.

Didier, what kind of setup are you planning to implement when zsys will support mirrors? Grub in efi partition with some kind of mechanism to replicate the updated grub right after an update?

To me the Ubuntu ZFS installer would be perfect as is, if only I could add the mirroring (no other features required). 
Could I use the install on a single disk and then replicate the partitions and attach the bpool and rpool on the second disk? 

My goal is trying to be forward compatible to avoid future pain :). 
What would you recommend?

**Comment by rlaager** [comment] 2020-09-14 13:50
I don’t see how two installs of GRUB is a problems in general. They would both point to the same real grub.cfg. In this specific case, if your system is switching between the two disks, it could be a problem if you didn’t update the second EFI GRUB grub.cfg when you renamed the dataset, which I forgot about when I told you to make the change in the other bug report.

@didrocks I’ll look into the history of bpool/grub and see if I can reproduce that problem. It sounds like that original is correct.

**Comment by ddnexus** [comment] 2020-09-14 14:11
@rlaager I did change the ubuntu-1 and ubuntu-2 grub.cfg too, but it looks like it didn't solve it. 
I also think that having 2 configs on 2 partitions pointing to the same (now) unique grub.cfg shoud work, unless update-grub triggers some other action besides updating the grub.cfg. I

I don't know enough to tell, but even having all the files pointing to the same config triggered the same problem, so it looks like it might be only prt of the tory.  I will try to reinstall grub.
